# Линтер подключаем именно в папку, созданную create-react-app
# Все зависимости линтера должны быть установлены на этом уровне,
# а не в корне проекта
# Не забудьте удалить ключ eslintConfig из package.json,
# автоматический созданный при запуске CRA
env:
  browser: true
  es2021: true


parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  testing-library/no-debug: 0
